### ISSUE TITLE
不支持redis.auth

### ISSUE THREAD

**Issue by faceair** [baoshan/wx#25]
在折腾[BAE](http://developer.baidu.com/wiki/index.php?title=docs/cplat/bae/redis)，使用redis是要授权的，所以现在的wx没办法使用。

要不就支持redis.auth，要不就支持接收redis实例，怎样比较好？

**Comment by faceair** [comment]
[node_redis](https://github.com/mranney/node_redis) 也不支持在 options 里面选择数据库，是否可以考虑换用 [ioredis](https://github.com/luin/ioredis) ？

**Comment by baoshan** [comment]
把全部键名加前缀`app_id`更好一点。

**Comment by faceair** [comment]
唉 主要是我想搭到coding上去，他们的[redis](http://docs.coding.io/services/redis)是需要认证选择数据库的
或者支持传入 Redis 实例也好

**Comment by baoshan** [comment]
`createClient`之后`select`一下看看。
