### ISSUE TITLE
希望添加全局的中间件

### ISSUE THREAD

**Issue by faceair** [baoshan/wx#33]
比如我想将语音识别结果当成文字信息来处理

**Comment by baoshan** [comment]
开通语音识别功能，用户每次发送语音给公众号时，微信会在推送的语音消息XML数据包中，增加一个Recongnition字段。

**Comment by faceair** [comment]
我知道，我是想说直接把Recongnition转成text消息的Content，让它看起来像一个文字消息

**Comment by baoshan** [comment]
直接用`wx.text`处理已被识别的语音请求怎样？

**Comment by faceair** [comment]
用户还可能自己额外处理下，比如保存录音源文件什么的，直接用wx.text也不太好吧
加全局的中间件更灵活一点

**Comment by faceair** [comment]
要不两个方案都加上？

**Comment by baoshan** [comment]
如果仍然用`wx.voice`处理，这个中间件做什么？只有两行嘛？

```
req.content or= req.recognition
next()
```

**Comment by faceair** [comment]
差不多，不过可能是三行，因为还要改`msgtype` : )
如果用户还希望保存录音源文件，也可以在这里处理。

比如我之前还有个需求 我希望验证OpenID，最好的办法是加个存储所有用户的OpenID的全局中间件，然后在网页里面通过显性的OpenID就可以验证这个用户是不是合法用户(给我们发过消息)，而不用担心OpenID被伪造。
