### ISSUE TITLE
请问一下，如果一台服务器上使用2个或2个以上的公共号，您的wx框架好像就不满足需求了。

### ISSUE THREAD

**Issue by yiqiuheng** [baoshan/wx#35]
需要修改ACCESS_TOKEN存储方式了吧？

**Comment by baoshan** [comment]
我应当在ACCESS_TOKEN后面补`app_id`。你愿意更正之后提交一个PR么？

**Comment by yiqiuheng** [comment]
这个改起来还是挺费劲的，改动的地方挺多，我看看怎么做吧~

**Comment by baoshan** [comment]
没那么复杂，已经改好了。有问题请反馈，谢谢。

**Comment by yiqiuheng** [comment]
最新写法是有问题的 ，微信要求URL必须是80端口，要在一台服务器上完成对2个不同微信的操作，必须是放在同一项目中有同一个端口服务，只能通过附带参数识别。

**Comment by baoshan** [comment]
你需要在Express前端加一个HTTP Server。

**Comment by baoshan** [comment]
同样意识到，一个`wx`实例是一个`express`的路由：
```
app.use '/app_1', wx_1
app.use '/app_2', wx_1
```
配合反向代理，如果仍然没有满意的方案，我们继续讨论。
