### ISSUE TITLE
__DELETED CONTENT__

### ISSUE THREAD

**Issue by wang-ling** [baoshan/wx#42]
__DELETED CONTENT__

**Comment by baoshan** [comment]
This is a public channel. For anything private, email me at `sheng@icmd.org`.

**Comment by wang-ling** [comment]
没有其他事啦。我下了。

**Comment by wang-ling** [comment]
谢谢你当初对我工作规范格式和质量的要求，让我在华为从事sql server数据库开发特别顺利，那种工作风格得到领导和很多同事的认可。让我经常会感谢你一下，不过我现在换了一家单位。话已带给你，一周后我再删掉此评论。
