### ISSUE TITLE
Issues on file upload.

### ISSUE THREAD

**Issue by yfwz100** [baoshan/wx#6]
I found that the code was using curl to upload multimedia file. It broke the application on Windows because of the absence of curl. Besides the issue on Windows, another problem is that it could leverage the native data pipeline on Node.js . It limits the data source to local files.

**Comment by calidion** [comment]
good point.

a little trick will do.

```javascript
      var media = fs.createReadStream(file);
      request.post({
        url: url,
        json: true,
        formData: { media: media, nonce: ''}
      }, function (error, response, body) {
        if (!error && response.statusCode == 200) {
          cb(false, body);
        } else {
          cb(true, {errorMessage: body});
        }
      });
```
